class AllSessionRaw:
    "This class merely contains the schema for session table"
    schema = {
    "namespace": "all_sessions_raw.avro",
    "type": "record",
    "name": "session",
    "fields": [
        {"name": "fullVisitorId"	, "type" : ["string" ,"null"]},
        {"name": "channelGrouping", "type": ["string", "null"]},
        {"name": "time"	, "type" : ["long" ,"null"]},
        {"name": "country", "type": ["string", "null"]},
        {"name": "city"	, "type" : ["string" ,"null"]},
        {"name": "totalTransactionRevenue"	, "type" : ["long" ,"null"]},
        {"name": "transactions"	, "type" : ["long" ,"null"]},
        {"name": "timeOnSite", "type": ["long", "null"]},
        {"name": "pageviews"	, "type" : ["long" ,"null"]},
        {"name": "sessionQualityDim"	, "type" : ["long" ,"null"]},
        {"name": "date"	, "type" : ["string" ,"null"]},
        {"name": "visitId", "type": ["long", "null"]},
        {"name": "type"	, "type" : ["string" ,"null"]},
        {"name": "productRefundAmount", "type": ["long", "null"]},
        {"name": "productQuantity", "type": ["long", "null"]},
        {"name": "productPrice"	, "type" : ["long" ,"null"]},
        {"name": "productRevenue", "type": ["long", "null"]},
        {"name": "productSKU", "type": ["string", "null"]},
        {"name": "v2ProductName"	, "type" : ["string" ,"null"]},
        {"name": "v2ProductCategory"	, "type" : ["string" ,"null"]},
        {"name": "productVariant", "type": ["string", "null"]},
        {"name": "currencyCode"	, "type" : ["string" ,"null"]},
        {"name": "itemQuantity"	, "type" : ["long" ,"null"]},
        {"name": "itemRevenue", "type": ["long", "null"]},
        {"name": "transactionRevenue", "type": ["long", "null"]},
        {"name": "transactionId"	, "type" : ["string" ,"null"]},
        {"name": "pageTitle"	, "type" : ["string" ,"null"]},
        {"name": "searchKeyword"	, "type" : ["string" ,"null"]},
        {"name": "pagePathLevel1", "type": ["string", "null"]},
        {"name": "eCommerceAction_type"	, "type" : ["string" ,"null"]},
        {"name": "eCommerceAction_step"	, "type" : ["long" ,"null"]},
        {"name": "eCommerceAction_option"	, "type" : ["string" ,"null"]},
        {"name": "unique_session_id", "type": ["string", "null"]}
    ]
}
    bq_table_schema = """
                            fullVisitorId:STRING,
                            channelGrouping:STRING,
                            time:INTEGER,
                            country:STRING,
                            city:STRING,
                            totalTransactionRevenue:INTEGER,
                            transactions:INTEGER,
                            timeOnSite:INTEGER,
                            pageviews:INTEGER,
                            sessionQualityDim:INTEGER,
                            date:STRING,
                            visitId:INTEGER,
                            type:STRING,
                            productRefundAmount:INTEGER,
                            productQuantity:INTEGER,
                            productPrice:INTEGER,
                            productRevenue:INTEGER,
                            productSKU:STRING,
                            v2ProductName:STRING,
                            v2ProductCategory:STRING,
                            productVariant:STRING,
                            currencyCode:STRING,
                            itemQuantity:INTEGER,
                            itemRevenue:INTEGER,
                            transactionRevenue:INTEGER,
                            transactionId:STRING,
                            pageTitle:STRING,
                            searchKeyword:STRING,
                            pagePathLevel1:STRING,
                            eCommerceAction_type:STRING,
                            eCommerceAction_step:INTEGER,
                            eCommerceAction_option:STRING,
                            unique_session_id:STRING
            """